language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: HZ8DcYPr1Q4GlStnHOFQcmTxkLz1RSorNALuhH5+jpdzx3Sg756lQjAXd9Xp6ln/9Z4dhhcYtEEkbLlztnOa2FbIwPP7R7/Kibx+shU65ZObCQNJuL21TPpq4gNAREAWTljN+BcGnk4VFPzss8aLMUSl+GowDe+Ri0awXUEh5AbPMdiecttnLRIIsMnabvCahy+MILxsB9rUEcF4pAAukxbD/kaUFC0up4/I/h6pRO9DA7yWjiEHAiSmHexT7JO8UkCF6JmrnZavmT9Pq5RlLwU0hPREXVfC1Zn15W8sGdLXsVhFfb8avZSAcLvAa53nDnOIKYfpmbvf7rpdjvp3IS4QKs5kliTTeHchwY2aZ46NRzGFN93JCJ9sZVUaVWh9GHscENI6AeEffTTRZR7fIu4yBUfO4w0rMFYgjb6NAVZUHNKCRAnw4ondifQWHfXnsboHRrMmzrwek+GdMtXD7KL/COHp8W9SkRdO/0fZcOSoCCn5SxLOFkAoQBCgwNPbI5zb5tqrpj8ZiYEdO1vCe4dafUKR3EDOLU+Kwn6J48BfzWTJZUQk9Xjs8AFsbZ51qQhU2d6SNdokXRUfotpaRdOy+Iu/3OLPIuhBrMwQ4mE5CLRoHmeO6Kh5+stVCNi6h5kJVeqr/3eHVaxiJ/4C0zC86FB++JS4EIc6BeQZb7I=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
