language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="http://repo.continuum.io/miniconda/Miniconda-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: lzP0Jb66DwRnQWHYMgj90jiyv28iZ4DrHjQUPXDQrIKqwrLPWKrrrxTg79SPvWz2Yty5iUKTkcqiyr/G52zDkRmWs3LkjrTsoWEs1p8wc2LQBY30LOJKyrqJizdldkSbjP8de3c0Kwk/FSzY3+elOQbnf4i7i9x7jJAmYJmKk1QH1eV3JJvOKtVm1XOZWXFk0iDceMsz20e3ttlxYefGWTcmJI2aqrV4QfBguSGbGuezBehCfdR9RIHO8Kl3mi6OCwRg3eY+FZl4hT14rU+EQzuGvE5x4NjAToICGkw7tYGhzxR75lr1zjvbBq0GmcsYVlBYY9L/Kg0Naej3NBvRnH7/8VvhMrBqSXtlLthg4A3H0qZ0gb2EbqdzC+f03IkGPxbcS67ssUsUZC3wmapfjs6IQUkcCKiFFw6+GSDhB51VO7qJ2GxgdQNLF2JWnowQVfy4khUISakjfG/XpFSH22NetsU1QaRrnMA7xXhe31946TZcM9/mDdv7AsONQF9eCG++nFKzwPer7uJRu8Qb7Mxe98+UoigGCfSt88pwobwDFeQYg4GxtEJJ0cJw2pAsx6ZYQVBsrKjfiKqkVclRKDbncyIzmfOsph2mn2XOshUOZwwytBi3x1VZbbRWd+X1NC5DLPz2BtqEr1BuQVIQoMLuwyGHhdiXCH/Qxaqyhhg=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
